### ISSUE TITLE
[2022-11-22T12:49:19.934] [ERROR] [bot:2323047125] - TypeError [Error]: Cannot read properties of undefined (reading 'setting')

### ISSUE THREAD

**Issue by guyingd** [kokkorojs/kokkoro-core#5]
[2022-11-22T12:49:19.934] [ERROR] [bot:2323047125] - TypeError [Error]: Cannot read properties of undefined (reading 'setting')
    at Bot.getSetting (/home/node_modules/kokkoro/lib/core/bot.js:193:45)
    at Object.next (/home/node_modules/kokkoro/lib/core/bot.js:58:38)
    at ConsumerObserver.next (/home/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
    at SafeSubscriber.Subscriber._next (/home/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26)
    at SafeSubscriber.Subscriber.next (/home/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /home/node_modules/rxjs/dist/cjs/internal/Subject.js:69:34
    at Object.errorContext (/home/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Bot.Subject.next (/home/node_modules/rxjs/dist/cjs/internal/Subject.js:59:24)
    at Bot.em (/home/node_modules/amesu/lib/client.js:516:18)
    at Bot.groupMsgListener (/home/node_modules/amesu/lib/internal/onlinepush.js:415:14)

**Comment by xueelf** [comment]
[v1.2.4](https://github.com/kokkorojs/kokkoro/releases/tag/v1.2.4) 已修复
